language: node_js

node_js:
 - node
 - lts/*
 - 8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --yes python3 php5-curl php5-cli

before_script:
  - ./node_modules/.bin/lerna bootstrap
